DROP TABLE IF EXISTS users;

CREATE TABLE users(
id INTEGER PRIMARY KEY,
username TEXT,
password TEXT,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);